#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
my $event = 'nethvoice-module-nethvplan-update';

event_actions($event, qw(
    initialize-default-databases 00
    nethvoice-module-nethvplan-conf 50
));

